# gan model, PathChar_GAN,RPathChar_GAN,RCGAN,TimeGAN, CotGAN,RCFGAN
gan_algo: HighRANKCPCFGAN
train: True
generator: ConditionalLSTM
dataset: fBM
device: cuda
gpu_id : "1"
seed: 0
n_lags: 11
past_path_length: 6
future_path_length: 5
data_feat_dim: 3


#hyperparameters:
lr_G: 0.002
lr_D: 0.005
D_steps_per_G_step: 1
G_steps_per_D_step: 2
R_steps_per_G_step: 100

batch_size: 1024
steps: 5000
gamma: 0.97
swa_step_start: 10000

#generator hyperparameter:
G_latent_dim: 5
G_hidden_dim: 128
grad_clip: 10
noise_scale: 2

lie_group: "unitary"
partition_size: 3
comment: ""
evaluate_every: 100

init_lambda: 0.1
MC_size: 400


# Rank 2 PCF
Rank_2_lie_degree: 13
Rank_2_num_samples: 10

# Regression:
R_input_dim: 4
R_hidden_dim: 128
R_num_layers: 2
R_iterations: 2000
lr_R: 0.001

# Finetune regression
Finetune_R_iterations: 400
Finetune_R_batch_size: 512
Finetune_R_max_tor: 20
Finetune_R_lr: 0.0000001

add_time: True
fine_tune_regression: True

rank_1_exp_dir: 'test'