# General configuration
device: cuda
seed: 0
gpu_id : "0"

data_dir: 'data/'

n_lags: 11
past_path_length: 6
future_path_length: 5
dataset: 'fBM'

Evaluation:
  test_ratio: 0.2
  n_eval: 5
  batch_size: 256
  metrics_enabled: [
    'discriminative_score',
    'predictive_score',
    # 'sig_mmd',
     'sigw1',
     'hist_loss',
     'acf_loss',
#     'cov_loss',
     'cross_corr',
    # 'permutation_test',
     'onnd',
     'cexp_loss'
#     'innd',
#     'icd',
#     'var',
#     'es'
    ]

  TestMetrics:
      discriminative_score:
        hidden_size: 32
        epochs : 10
        num_layers: 2
        batch_size: 128

      predictive_score:
        hidden_size: 32
        epochs : 10
        num_layers: 2
        batch_size: 128

      sig_mmd:
        depth: 5

      sigw1_loss:
        depth: 2
        normalise: False

      hist_loss:
        n_bins: 50

      cross_corr:
        max_lags: 5

      acf_loss:
        stationary: False # False, depend on dataset
        keep_init: False
        max_lags: 64

      cov_loss: None

      permutation_test:
        n_permutation: 5

      onnd: None

      innd: None

      icd: None

      var:
        alpha: 0.05

      es:
        alpha: 0.05

      cexp_loss:
        mc_size: 200