# gan model, PathChar_GAN,RPathChar_GAN,RCGAN,TimeGAN, CotGAN
gan_algo: RCGAN
dataset: Stock

device: cuda
seed: 3
gpu_id : "0"
n_lags: 10
data_feat_dim: 5

#hyperparameters:
lr_G: 0.001
lr_D: 0.001
D_steps_per_G_step: 2
batch_size: 64
steps: 15000
gamma: 0.97
grad_clip: 10
#
swa_step_start: 25000
#generator hyperparameter:
G_input_dim: 5
G_latent_dim: 5
G_hidden_dim: 32
G_num_layers: 2

init_fixed: False
noise_scale : 0.1
#discriminator hyperparameter:
D_hidden_dim: 32
D_num_layers: 2
D_out_dim: 5

BM: True
init_range: 1
past_path_length: 5


comment:
evaluate_every: 500